// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need session-level Postgres features (advisory locks) that a transaction-mode
    // pooler (e.g. Supabase's port 6543) breaks. DIRECT_URL should point at a session pooler or
    // direct connection; the app's runtime PrismaClient (src/lib/db.ts) uses DATABASE_URL
    // independently via its own adapter and never reads this file, so the two can safely differ.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
